(setq viper-inhibit-startup-message 't)
(setq viper-expert-level '5)
(setq viper-want-ctl-h-help t)
(setq viper-ex-style-motion nil)
(define-key viper-minibuffer-map (kbd "RET") nil)
(viper-buffer-search-enable)
