;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from among.el

(register-definition-prefixes "among" '("among"))


;;; Generated autoloads from aoc.el

(register-definition-prefixes "aoc" '("aoc"))


;;; Generated autoloads from apt-progress.el

(register-definition-prefixes "apt-progress" '("ansi-color-apply-on-region"))


;;; Generated autoloads from arXiv.el

(register-definition-prefixes "arXiv" '("arXiv-"))


;;; Generated autoloads from block-undo.el

(register-definition-prefixes "block-undo" '("block-undo"))


;;; Generated autoloads from bqn-mode.el

(register-definition-prefixes "bqn-mode" '("bqn-"))


;;; Generated autoloads from calc-exchange-rates.el

(register-definition-prefixes "calc-exchange-rates" '("calc-exchange-rates"))


;;; Generated autoloads from calc-rref.el

(register-definition-prefixes "calc-rref" '("calc" "rref-raw"))


;;; Generated autoloads from calc-simplex.el

(register-definition-prefixes "calc-simplex" '("actual-basis" "dict" "display-index" "format-" "latexdict" "pivot"))


;;; Generated autoloads from comint-extras.el

(register-definition-prefixes "comint-extras" '("newline-substitution-comint-sender" "send-to-comint"))


;;; Generated autoloads from ecomplete-extras.el

(register-definition-prefixes "ecomplete-extras" '("add-email-to-ecomplete" "compose-mail-to" "ecomplete--read-address" "email--name+address" "remove-email-from-ecomplete"))


;;; Generated autoloads from eshell-extras.el

(register-definition-prefixes "eshell-extras" '("eshell" "interactive-cd"))


;;; Generated autoloads from eval-region-advice.el

(register-definition-prefixes "eval-region-advice" '("eval-region-if-active"))


;;; Generated autoloads from ffap-eshell.el

(register-definition-prefixes "ffap-eshell" '("ffap-eshell-mode" "guess-directory-from-"))


;;; Generated autoloads from gptel-extras.el

(register-definition-prefixes "gptel-extras" '("gptel-extras-"))


;;; Generated autoloads from help-extras.el

(register-definition-prefixes "help-extras" '("command-of-the-day" "cotd" "show-help"))


;;; Generated autoloads from isearch-extras.el

(register-definition-prefixes "isearch-extras" '("isearch-"))


;;; Generated autoloads from lem-imenu.el

(register-definition-prefixes "lem-imenu" '("lem-imenu-"))


;;; Generated autoloads from man-help.el

(register-definition-prefixes "man-help" '("read-shell-command"))


;;; Generated autoloads from message-extras.el

(register-definition-prefixes "message-extras" '("cycle-from-address" "message-lint" "set-smtp-server"))


;;; Generated autoloads from narrow-extras.el

(register-definition-prefixes "narrow-extras" '("narrow-"))


;;; Generated autoloads from ob-bqn.el

(register-definition-prefixes "ob-bqn" '("ob-bqn-value" "org-babel-execute:bqn"))


;;; Generated autoloads from ob-goal.el

(register-definition-prefixes "ob-goal" '("goal-mode" "ob-goal-value" "org-babel-execute:goal"))


;;; Generated autoloads from ob-k.el

(register-definition-prefixes "ob-k" '("k-mode" "ob-k-value" "org-babel-execute:k"))


;;; Generated autoloads from org-extras.el

(register-definition-prefixes "org-extras" '("org-" "prefix-all-lines"))


;;; Generated autoloads from org-ql-usual-files.el

(register-definition-prefixes "org-ql-usual-files" '("org-ql-usual-files"))


;;; Generated autoloads from shr-heading.el

(register-definition-prefixes "shr-heading" '("shr-heading-"))


;;; Generated autoloads from text-extras.el

(register-definition-prefixes "text-extras" '("apply-macro-to-lines-of-paragraph" "backward-to-whitespace" "copy-word-from-above" "dabbrev-" "define-" "duplicate-line-kill-word" "echo-area-tooltips" "forward-to-whitespace" "goto-random-line" "kill-inside-sexp" "mark-" "pipe-region" "random-line-map" "text-to-clipboard" "unfill-paragraph" "unwrap-"))


;;; Generated autoloads from tmp-buffer.el

(register-definition-prefixes "tmp-buffer" '("tmp-buffer"))


;;; Generated autoloads from topaz-paste.el

(register-definition-prefixes "topaz-paste" '("topaz-paste-"))


;;; Generated autoloads from vc-extras.el

(register-definition-prefixes "vc-extras" '("log-view-save-commit-hash" "vc-git-commit"))


;;; Generated autoloads from vimgolf.el

(register-definition-prefixes "vimgolf" '("vimgolf"))


;;; Generated autoloads from visiting-buffer.el

(register-definition-prefixes "visiting-buffer" '("visiting-buffer-"))


;;; Generated autoloads from webjump-extras.el

(register-definition-prefixes "webjump-extras" '("webjump"))


;;; Generated autoloads from window-extras.el

(register-definition-prefixes "window-extras" '("screenshot" "toggle-" "transpose-windows"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
