;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from among.el

(register-definition-prefixes "among" '("among"))


;;; Generated autoloads from aoc.el

(register-definition-prefixes "aoc" '("aoc"))


;;; Generated autoloads from apt-progress.el

(register-definition-prefixes "apt-progress" '("ansi-color-apply-on-region"))


;;; Generated autoloads from arXiv.el

(autoload 'arXiv-pdf "arXiv"
"Open the PDF version of PAPER from the arXiv in Emacs.
A ragtag bunch of ad hoc formats are recognized for PAPER.
If EXTERNAL is non-nil use an external browser.

(fn PAPER &optional EXTERNAL)" t)
(autoload 'arXiv-copy-url "arXiv"
"Copy PAPER's URL to the kill-ring.

(fn PAPER)" t)
(autoload 'arXiv-show "arXiv"
"Popup a buffer with the title, authors and abstract of PAPER.
A ragtag bunch of ad hoc formats are recognized for PAPER.

(fn PAPER)" t)
(autoload 'arXiv-capture "arXiv"
"Capture Org entry for arXiv PAPER at point.
(This depends on the `org-capture' template \"a\" just inserting
the kill ring head. 😬)

(fn PAPER)" t)
(register-definition-prefixes "arXiv" '("arXiv--"))


;;; Generated autoloads from block-undo.el

(register-definition-prefixes "block-undo" '("block-undo"))


;;; Generated autoloads from bqn-mode.el

(register-definition-prefixes "bqn-mode" '("bqn-"))


;;; Generated autoloads from calc-exchange-rates.el

(register-definition-prefixes "calc-exchange-rates" '("calc-exchange-rates"))


;;; Generated autoloads from calc-rref.el

(register-definition-prefixes "calc-rref" '("calc" "rref-raw"))


;;; Generated autoloads from calc-simplex.el

(register-definition-prefixes "calc-simplex" '("actual-basis" "dict" "display-index" "format-" "latexdict" "pivot"))


;;; Generated autoloads from comint-extras.el

(register-definition-prefixes "comint-extras" '("newline-substitution-comint-sender" "send-to-comint"))


;;; Generated autoloads from ecomplete-extras.el

(autoload 'add-email-to-ecomplete "ecomplete-extras"
"Add email address to ecomplete's database.

(fn EMAIL)" t)
(autoload 'remove-email-from-ecomplete "ecomplete-extras"
"Remove email address from ecomplete's database.

(fn EMAIL)" t)
(autoload 'compose-mail-to "ecomplete-extras"
"Compose email to ADDRESS from ecomplete's database.

(fn ADDRESS)" t)
(register-definition-prefixes "ecomplete-extras" '("ecomplete--read-address" "email--name+address"))


;;; Generated autoloads from eshell-extras.el

(autoload 'interactive-cd "eshell-extras"
"Prompt for a directory and cd to it.

(fn DIR)" t)
(autoload 'eshell/for-each "eshell-extras"
"Run command once for each argument.

(fn CMD &rest ARGS)")
(autoload 'eshell/in-term "eshell-extras"
"Run shell command in term buffer.

(fn PROG &rest ARGS)")
(autoload 'eshell-bookmark-jump "eshell-extras"
"Default bookmark handler for Eshell buffers.

(fn BOOKMARK)")


;;; Generated autoloads from eval-region-advice.el

(register-definition-prefixes "eval-region-advice" '("eval-region-if-active"))


;;; Generated autoloads from ffap-eshell.el

(register-definition-prefixes "ffap-eshell" '("ffap-eshell-mode" "guess-directory-from-"))


;;; Generated autoloads from gptel-extras.el

(register-definition-prefixes "gptel-extras" '("gptel-extras-"))


;;; Generated autoloads from help-extras.el

(autoload 'command-of-the-day "help-extras"
"Show the documentation for a random command." t)
(defalias 'cotd #'command-of-the-day)
(autoload 'show-help "help-extras"
"Show the *Help* buffer." t)


;;; Generated autoloads from isearch-extras.el

(register-definition-prefixes "isearch-extras" '("isearch-"))


;;; Generated autoloads from lem-imenu.el

(autoload 'lem-imenu-setup "lem-imenu"
"Setup imenu in lem buffers.
Add this function to `lem-mode-hook'.")
(register-definition-prefixes "lem-imenu" '("lem-imenu--"))


;;; Generated autoloads from man-help.el

(register-definition-prefixes "man-help" '("read-shell-command"))


;;; Generated autoloads from message-extras.el

(autoload 'cycle-from-address "message-extras"
"Cycle between my email addresses." t)
(autoload 'set-smtp-server "message-extras"
"Set the stmp server according to the from field.
Add to `message-send-hook'.")
(autoload 'message-lint "message-extras"
"Check for missing subject or attachments.
Add to `message-send-hook'.")


;;; Generated autoloads from narrow-extras.el

(register-definition-prefixes "narrow-extras" '("narrow-"))


;;; Generated autoloads from ob-bqn.el

(register-definition-prefixes "ob-bqn" '("ob-bqn-value" "org-babel-execute:bqn"))


;;; Generated autoloads from ob-goal.el

(register-definition-prefixes "ob-goal" '("goal-mode" "ob-goal-value" "org-babel-execute:goal"))


;;; Generated autoloads from ob-k.el

(register-definition-prefixes "ob-k" '("k-mode" "ob-k-value" "org-babel-execute:k"))


;;; Generated autoloads from org-extras.el

(register-definition-prefixes "org-extras" '("org-" "prefix-all-lines"))


;;; Generated autoloads from org-ql-usual-files.el

(register-definition-prefixes "org-ql-usual-files" '("org-ql-usual-files"))


;;; Generated autoloads from shr-heading.el

(autoload 'shr-heading-next "shr-heading"
"Move forward by ARG headings (any h1-h4).
If ARG is negative move backwards, ARG defaults to 1.

(fn &optional ARG)" t)
(autoload 'shr-heading-previous "shr-heading"
"Move backward by ARG headings (any h1-h4).
If ARG is negative move forwards instead, ARG defaults to 1.

(fn &optional ARG)" t)
(autoload 'shr-heading-setup-imenu "shr-heading"
"Setup imenu for h1-h4 headings in eww buffer.
Add this function to appropriate major mode hooks such as
`eww-mode-hook' or `elfeed-show-mode-hook'.")
(register-definition-prefixes "shr-heading" '("shr-heading-"))


;;; Generated autoloads from text-extras.el

(autoload 'copy-word-from-above "text-extras"
"Copy ARG words from the nonblank line above. With a negative
argument, copy the rest of the line.

(fn ARG)" t)
(autoload 'duplicate-line-kill-word "text-extras"
"Duplicate the current line and kill the word at point in the duplicate." t)
(autoload 'goto-random-line "text-extras"
"Goto a random line in the buffer." t)
(autoload 'pipe-region "text-extras"
"Pipe region through shell command. If the mark is inactive,
pipe whole buffer.

(fn START END COMMAND)" t)
(autoload 'forward-to-whitespace "text-extras"
"Move forward to the end of the next sequence of non-whitespace
characters. With argument, do this that many times.

(fn ARG)" t)
(autoload 'backward-to-whitespace "text-extras"
"Move backward to the beginning of the previous sequence of
non-whitespace characters. With argument, do this that many
times.

(fn ARG)" t)
(autoload 'mark-inside-sexp "text-extras"
"Mark inside a sexp." t)
(autoload 'kill-inside-sexp "text-extras"
"Kill inside a sexp." t)
(autoload 'unwrap-sexp "text-extras"
"Unwrap a sexp." t)
(autoload 'unwrap-mark-sexp "text-extras"
"Unwrap a sexp and mark the contents." t)
(autoload 'dabbrev-next "text-extras"
"Insert the next ARG words from where previous expansion was found.

(fn ARG)" t)
(autoload 'dabbrev-complete-next "text-extras"
"Choose a continuation for the previous expansion with completion." t)
(autoload 'text-to-clipboard "text-extras"
"Pop up a temporary buffer to collect text to send to the clipboard.
The pop up buffer is in `markdown-mode' and uses the TeX input
method.  Use \\<text-to-clipboard-minor-mode-map>\\[text-to-clipboard--done] to send the buffer contents to the clipboard
and quit the window, killing the buffer.

If the region is active, use the region as the initial contents
for the pop up buffer." t)
(autoload 'apply-macro-to-lines-of-paragraph "text-extras"
"Apply last keyboard macro to each line in the current paragraph.
If a macro is being recorded, it is ended and then applied to the
remaining lines of the paragraph." t)
(autoload 'echo-area-tooltips "text-extras"
"Show tooltips in the echo area automatically for current buffer.")
(register-definition-prefixes "text-extras" '("define-" "mark-" "random-line-map" "text-to-clipboard-"))


;;; Generated autoloads from tmp-buffer.el

(register-definition-prefixes "tmp-buffer" '("tmp-buffer"))


;;; Generated autoloads from topaz-paste.el

(autoload 'topaz-paste-region "topaz-paste"
"Save topaz paste URL for region contents on the kill-ring.

(fn BEGIN END)" t)
(autoload 'topaz-paste-buffer "topaz-paste"
"Save topaz paste URL for buffer contents on the kill-ring." t)


;;; Generated autoloads from vc-extras.el

(autoload 'log-view-save-commit-hash "vc-extras"
"Save commit hash of log entry at point to `kill-ring'." t)
(autoload 'vc-git-commit "vc-extras"
"Run git commit -m MESSAGE.
Interactively MESSAGE is just \"Merge resolving conflicts\", but
with a prefix argument you are prompted for a message.

(fn MESSAGE)" t)


;;; Generated autoloads from vimgolf.el

(register-definition-prefixes "vimgolf" '("vimgolf"))


;;; Generated autoloads from visiting-buffer.el

(register-definition-prefixes "visiting-buffer" '("visiting-buffer-"))


;;; Generated autoloads from webjump-extras.el

(register-definition-prefixes "webjump-extras" '("webjump"))


;;; Generated autoloads from window-extras.el

(register-definition-prefixes "window-extras" '("screenshot" "toggle-" "transpose-windows"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
